"""Provider-agnostic core: the types and protocols a provider is written against.

The agent and its session live one layer out, in ``agentshim/agent.py``:
turning a provider name into a provider means importing ``providers``, which
this package may not do.
"""

from __future__ import annotations

from .clock import Clock, StopSignal, SystemClock
from .env import interactive_env
from .errors import (
    AgentShimError,
    CliCheckError,
    CliExitError,
    CliNotFoundError,
    CliTimeoutError,
    FailureKind,
    McpConfigError,
    ProcessClosedError,
    ProviderCapabilityError,
    ReapError,
    SchemaDialectError,
    SessionResumeError,
)
from .events import (
    AgentEvent,
    AgentEventHandler,
    AssistantText,
    CompositeEventHandler,
    ConsoleEventHandler,
    EventHandlerBase,
    Lifecycle,
    NullEventHandler,
    ProviderError,
    RawOutput,
    Reasoning,
    RunFinished,
    RunStarted,
    SessionStarted,
    SkillInvoked,
    SkillsDiscovered,
    Stderr,
    ToolCall,
    ToolResult,
    UsageReport,
    compose_event_handlers,
)
from .home import prepare_config_home
from .ids import IdAllocator, RandomIds
from .mcp import (
    ConfigFileInstallation,
    FlagsInstallation,
    HttpMcpServer,
    McpServer,
    McpTransport,
    NoopInstallation,
    StdioMcpServer,
    install_config_file,
)
from .permissions import ApprovalPolicy, NativeMode, NativePermissions
from .pricing import ModelPricing, PricingTable, cost_usd, default_pricing, price_for
from .profile import (
    ConfigScope,
    McpMechanism,
    McpScope,
    OutputSchemaStyle,
    ProviderProfile,
    SchemaDialect,
    SkillScope,
    SkillSignal,
)
from .provider import (
    ArgvContext,
    ContextualStreamParser,
    McpInstallation,
    ParsedTurn,
    ParserContext,
    Provider,
    StreamParser,
)
from .schema import compact_json, dialect_problems, materialize, normalize
from .skills import SkillSummary, SkillTracker
from .stream import ToolTracker, parse_json_object
from .turn import OutputSchema, TurnRequest, TurnResult
from .usage import ProviderUsage, TokenUsage, TokenWeights, normalized_usage

__all__ = [
    "AgentEvent",
    "AgentEventHandler",
    "AgentShimError",
    "ApprovalPolicy",
    "ArgvContext",
    "AssistantText",
    "CliCheckError",
    "CliExitError",
    "CliNotFoundError",
    "CliTimeoutError",
    "Clock",
    "CompositeEventHandler",
    "ConfigFileInstallation",
    "ConfigScope",
    "ConsoleEventHandler",
    "ContextualStreamParser",
    "EventHandlerBase",
    "FailureKind",
    "FlagsInstallation",
    "HttpMcpServer",
    "IdAllocator",
    "Lifecycle",
    "McpConfigError",
    "McpInstallation",
    "McpMechanism",
    "McpScope",
    "McpServer",
    "McpTransport",
    "ModelPricing",
    "NativeMode",
    "NativePermissions",
    "NoopInstallation",
    "NullEventHandler",
    "OutputSchema",
    "OutputSchemaStyle",
    "ParsedTurn",
    "ParserContext",
    "PricingTable",
    "ProcessClosedError",
    "Provider",
    "ProviderCapabilityError",
    "ProviderError",
    "ProviderProfile",
    "ProviderUsage",
    "RandomIds",
    "RawOutput",
    "ReapError",
    "Reasoning",
    "RunFinished",
    "RunStarted",
    "SchemaDialect",
    "SchemaDialectError",
    "SessionResumeError",
    "SessionStarted",
    "SkillInvoked",
    "SkillScope",
    "SkillSignal",
    "SkillSummary",
    "SkillTracker",
    "SkillsDiscovered",
    "Stderr",
    "StdioMcpServer",
    "StopSignal",
    "StreamParser",
    "SystemClock",
    "TokenUsage",
    "TokenWeights",
    "ToolCall",
    "ToolResult",
    "ToolTracker",
    "TurnRequest",
    "TurnResult",
    "UsageReport",
    "compact_json",
    "compose_event_handlers",
    "cost_usd",
    "default_pricing",
    "dialect_problems",
    "install_config_file",
    "interactive_env",
    "materialize",
    "normalize",
    "normalized_usage",
    "parse_json_object",
    "prepare_config_home",
    "price_for",
]
