"""agentshim: run coding-agent CLIs and understand what they printed.

Everything importable from this module is supported API. The test doubles
live in ``agentshim.testing``.
"""

from __future__ import annotations

from .agent import AgentSession, CliAgent
from .core import (
    AgentEvent,
    AgentEventHandler,
    AgentShimError,
    ArgvContext,
    AssistantText,
    CliCheckError,
    CliExitError,
    CliNotFoundError,
    CliTimeoutError,
    CompositeEventHandler,
    ConfigFileInstallation,
    ConsoleEventHandler,
    EventHandlerBase,
    FlagsInstallation,
    HttpMcpServer,
    Lifecycle,
    McpConfigError,
    McpInstallation,
    McpMechanism,
    McpServer,
    NoopInstallation,
    NullEventHandler,
    OutputSchema,
    OutputSchemaStyle,
    ParsedTurn,
    Provider,
    ProviderCapabilityError,
    ProviderError,
    ProviderProfile,
    ProviderUsage,
    RawOutput,
    Reasoning,
    RunFinished,
    RunStarted,
    SchemaDialect,
    SchemaDialectError,
    SessionResumeError,
    SessionStarted,
    Stderr,
    StdioMcpServer,
    StreamParser,
    TokenUsage,
    ToolCall,
    ToolResult,
    ToolTracker,
    TurnRequest,
    TurnResult,
    UsageReport,
    compact_json,
    compose_event_handlers,
    dialect_problems,
    install_config_file,
    interactive_env,
    materialize,
    normalize,
    parse_json_object,
)
from .execution import (
    CallbackCommandStreamSink,
    CommandExecutor,
    CommandHandle,
    CommandRequest,
    CommandResult,
    CommandStreamSink,
    HostCommandExecutor,
    NullSink,
    TransformingExecutor,
)
from .providers import get_provider, provider_names

__version__ = "0.6.0"

__all__ = [
    "AgentEvent",
    "AgentEventHandler",
    "AgentSession",
    "AgentShimError",
    "ArgvContext",
    "AssistantText",
    "CallbackCommandStreamSink",
    "CliAgent",
    "CliCheckError",
    "CliExitError",
    "CliNotFoundError",
    "CliTimeoutError",
    "CommandExecutor",
    "CommandHandle",
    "CommandRequest",
    "CommandResult",
    "CommandStreamSink",
    "CompositeEventHandler",
    "ConfigFileInstallation",
    "ConsoleEventHandler",
    "EventHandlerBase",
    "FlagsInstallation",
    "HostCommandExecutor",
    "HttpMcpServer",
    "Lifecycle",
    "McpConfigError",
    "McpInstallation",
    "McpMechanism",
    "McpServer",
    "NoopInstallation",
    "NullEventHandler",
    "NullSink",
    "OutputSchema",
    "OutputSchemaStyle",
    "ParsedTurn",
    "Provider",
    "ProviderCapabilityError",
    "ProviderError",
    "ProviderProfile",
    "ProviderUsage",
    "RawOutput",
    "Reasoning",
    "RunFinished",
    "RunStarted",
    "SchemaDialect",
    "SchemaDialectError",
    "SessionResumeError",
    "SessionStarted",
    "Stderr",
    "StdioMcpServer",
    "StreamParser",
    "TokenUsage",
    "ToolCall",
    "ToolResult",
    "ToolTracker",
    "TransformingExecutor",
    "TurnRequest",
    "TurnResult",
    "UsageReport",
    "__version__",
    "compact_json",
    "compose_event_handlers",
    "dialect_problems",
    "get_provider",
    "install_config_file",
    "interactive_env",
    "materialize",
    "normalize",
    "parse_json_object",
    "provider_names",
]
