"""agentshim: run coding-agent CLIs and understand what they printed.

Everything importable from this module is supported API. The test doubles
live in ``agentshim.testing``.
"""

from __future__ import annotations

from .agent import AgentSession, CliAgent
from .core import (
    AgentEvent,
    AgentEventHandler,
    AgentShimError,
    ArgvContext,
    AssistantText,
    CliCheckError,
    CliExitError,
    CliNotFoundError,
    CliTimeoutError,
    CompositeEventHandler,
    ConfigFileInstallation,
    ConfigScope,
    ConsoleEventHandler,
    ContextualStreamParser,
    EventHandlerBase,
    FailureKind,
    FlagsInstallation,
    HttpMcpServer,
    Lifecycle,
    McpConfigError,
    McpInstallation,
    McpMechanism,
    McpScope,
    McpServer,
    McpTransport,
    ModelPricing,
    NoopInstallation,
    NullEventHandler,
    OutputSchema,
    OutputSchemaStyle,
    ParsedTurn,
    ParserContext,
    PricingTable,
    Provider,
    ProviderCapabilityError,
    ProviderError,
    ProviderProfile,
    ProviderUsage,
    RawOutput,
    Reasoning,
    RunFinished,
    RunStarted,
    SchemaDialect,
    SchemaDialectError,
    SessionResumeError,
    SessionStarted,
    SkillInvoked,
    SkillScope,
    SkillsDiscovered,
    SkillSignal,
    SkillSummary,
    SkillTracker,
    Stderr,
    StdioMcpServer,
    StreamParser,
    TokenUsage,
    TokenWeights,
    ToolCall,
    ToolResult,
    ToolTracker,
    TurnRequest,
    TurnResult,
    UsageReport,
    compact_json,
    compose_event_handlers,
    cost_usd,
    default_pricing,
    dialect_problems,
    install_config_file,
    interactive_env,
    materialize,
    normalize,
    normalized_usage,
    parse_json_object,
    prepare_config_home,
    price_for,
)
from .execution import (
    CallbackCommandStreamSink,
    CommandExecutor,
    CommandHandle,
    CommandRequest,
    CommandResult,
    CommandStreamSink,
    HostCommandExecutor,
    NullSink,
    TransformingExecutor,
)
from .providers import get_provider, provider_names
from .providers.claude import ClaudeHook, ClaudeProvider, SandboxConfig
from .providers.codex import CodexProvider, CodexSandboxConfig
from .providers.copilot import CopilotProvider
from .providers.gemini import GeminiProvider
from .providers.opencode import OpencodeProvider

__version__ = "0.14.1"

__all__ = [
    "AgentEvent",
    "AgentEventHandler",
    "AgentSession",
    "AgentShimError",
    "ArgvContext",
    "AssistantText",
    "CallbackCommandStreamSink",
    "ClaudeHook",
    "ClaudeProvider",
    "CliAgent",
    "CliCheckError",
    "CliExitError",
    "CliNotFoundError",
    "CliTimeoutError",
    "CodexProvider",
    "CodexSandboxConfig",
    "CommandExecutor",
    "CommandHandle",
    "CommandRequest",
    "CommandResult",
    "CommandStreamSink",
    "CompositeEventHandler",
    "ConfigFileInstallation",
    "ConfigScope",
    "ConsoleEventHandler",
    "ContextualStreamParser",
    "CopilotProvider",
    "EventHandlerBase",
    "FailureKind",
    "FlagsInstallation",
    "GeminiProvider",
    "HostCommandExecutor",
    "HttpMcpServer",
    "Lifecycle",
    "McpConfigError",
    "McpInstallation",
    "McpMechanism",
    "McpScope",
    "McpServer",
    "McpTransport",
    "ModelPricing",
    "NoopInstallation",
    "NullEventHandler",
    "NullSink",
    "OpencodeProvider",
    "OutputSchema",
    "OutputSchemaStyle",
    "ParsedTurn",
    "ParserContext",
    "PricingTable",
    "Provider",
    "ProviderCapabilityError",
    "ProviderError",
    "ProviderProfile",
    "ProviderUsage",
    "RawOutput",
    "Reasoning",
    "RunFinished",
    "RunStarted",
    "SandboxConfig",
    "SchemaDialect",
    "SchemaDialectError",
    "SessionResumeError",
    "SessionStarted",
    "SkillInvoked",
    "SkillScope",
    "SkillSignal",
    "SkillSummary",
    "SkillTracker",
    "SkillsDiscovered",
    "Stderr",
    "StdioMcpServer",
    "StreamParser",
    "TokenUsage",
    "TokenWeights",
    "ToolCall",
    "ToolResult",
    "ToolTracker",
    "TransformingExecutor",
    "TurnRequest",
    "TurnResult",
    "UsageReport",
    "__version__",
    "compact_json",
    "compose_event_handlers",
    "cost_usd",
    "default_pricing",
    "dialect_problems",
    "get_provider",
    "install_config_file",
    "interactive_env",
    "materialize",
    "normalize",
    "normalized_usage",
    "parse_json_object",
    "prepare_config_home",
    "price_for",
    "provider_names",
]
